:: https://winstall.app/
winget install Microsoft.WindowsTerminal
winget install Git.Git
winget install Google.Chrome
winget install Mozilla.Firefox
winget install Microsoft.VisualStudioCode-System-x64
winget install Meld.Meld
winget install dnGrep.dnGrep 
winget install Insomnia.Insomnia
winget install Microsoft.Teams 
winget install SlackTechnologies.Slack
winget install Discord.Discord
winget install VideoLAN.VLC
winget install stax76.mpv.net
winget install Deezer.Deezer
winget install OBSProject.OBSStudio
winget install Audacity.Audacity
winget install Valve.Steam
winget install EpicGames.EpicGamesLauncher
winget install GIMP.GIMP
winget install Inkscape.Inkscape
winget install qBittorrent.qBittorrent
winget install Bitwarden.Bitwarden
winget install OpenJS.Nodejs
winget install 7zip.7zip
winget install Docker.DockerDesktop
winget install Microsoft.VisualStudio.Community