code --install-extension MS-vsliveshare.vsliveshare-pack
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension eamodio.gitlens
code --install-extension pflannery.vscode-versionlens
code --install-extension gruntfuggly.todo-tree
code --install-extension eamodio.toggle-excluded-files
code --install-extension editorconfig.editorconfig
code --install-extension mikestead.dotenv
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension wix.vscode-import-cost
code --install-extension esbenp.prettier-vscode
code --install-extension orta.vscode-jest
code --install-extension wallabyjs.quokka-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension stylelint.vscode-stylelint
code --install-extension csstools.postcss
code --install-extension davidanson.vscode-markdownlint
code --install-extension knisterpeter.vscode-commitizen
code --install-extension msjsdiag.vscode-react-native
code --install-extension jounqin.vscode-mdx
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension Prisma.vscode-graphql
code --install-extension denoland.vscode-deno
code --install-extension swellaby.rust-pack
code --install-extension swellaby.vscode-rust-test-adapter